apiVersion: v1
kind: Service
metadata:
  name: project-flask
  labels:
    app: flask
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-flask
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: sukhotin/project_flask_http
        imagePullPolicy: Always
        ports:
        - containerPort: 5000